packages:
  - "."

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

confirmModulesPurge: false

minimumReleaseAgeExclude:
  - "@vitest/mocker@5.0.1"
  - "@vitest/spy@5.0.1"
  - "vitest@5.0.1"
